---
- name: ensure APT key
  apt_key:
    id: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    state: present

- name: ensure APT repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    state: present

- name: install linux-image-extra for aufs storage driver support
  package:
    name: "linux-image-extra-{{ ansible_kernel }}"
    state: latest
  notify: restart docker
