---

- name: include os specific installation tasks
  include: "{{ item }}"
  with_first_found:
    - 'install/{{ ansible_distribution }}.yml'
    - 'install/{{ ansible_os_family }}.yml'

- name: install docker-engine
  package:
    name: docker-engine
    state: latest
  notify: restart docker

- name: ensure daemon is running
  service:
    name: docker
    state: started
    enabled: yes

- name: ensure the docker group
  group:
    name: docker
    state: present

- name: ensure users are in the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
